### ISSUE TITLE
Pre-Patch Update

### ISSUE THREAD

**Issue by missiah** [Metalhearf/HideBattleNetFriends#1]
The new Retail update apparently broke the addon

**Comment by Metalhearf** [comment]
Thank you for your message. 
Indeed 10.0.0 broke a lot of things: I think I will not continue to maintain this addon on the Retail branch (Dragonflight).

However, I noticed that [the original developer](https://www.curseforge.com/members/skye_v5/projects) has posted a new version of his add-on: it's much more customizable and accomplished than this raw version. 

I invite you to check out his work : [right here](https://www.curseforge.com/wow/addons/hide-battle-net). 

Regards,

**Comment by missiah** [comment]
cool thanks
